theme: jekyll-theme-minimal
title: jsblocks - Better JavaScript MV-ish Framework ***
description: From simple user interfaces to complex single-page applications using faster, server-side rendered and easy to learn framework
